import React from 'react';
import {WorkElement,PAGE_W,PAGE_H} from '@/lib/work-layout';
export const printCSS=`.wi-print{font-family:Arial,Helvetica,sans-serif;color:#18283f;background:#fff;box-sizing:border-box;font-size:18px;line-height:1.5}.wi-print *{box-sizing:border-box}.wi-rich{font-size:18px;line-height:1.5;overflow-wrap:anywhere;color:#18283f}.wi-rich p,.wi-rich div{margin:0 0 10px}.wi-rich ul{list-style:disc;padding-left:28px;margin:10px 0}.wi-rich ol{list-style:decimal;padding-left:28px;margin:10px 0}.wi-rich li{margin-bottom:5px}.wi-rich h1{font-size:32px;margin:12px 0}.wi-rich h2{font-size:26px;margin:12px 0}.wi-rich h3{font-size:22px;margin:10px 0}.wi-rich table{border-collapse:collapse;width:100%;table-layout:fixed;margin:10px 0}.wi-rich td,.wi-rich th{border:1px solid #9faec2;padding:8px;text-align:left;min-width:30px;vertical-align:top;overflow-wrap:anywhere}.wi-rich th{background:#edf2f8;font-weight:bold}.wi-rich a{color:#234fba;text-decoration:underline}.wi-rich blockquote{border-left:3px solid #a5b6cf;margin:8px;padding-left:16px}.wi-rich font[size="2"]{font-size:14px}.wi-rich font[size="3"]{font-size:18px}.wi-rich font[size="4"]{font-size:22px}.wi-rich font[size="5"]{font-size:28px}.wi-rich font[size="6"]{font-size:36px}.wi-rich font[size="7"]{font-size:44px}`;
export function ElementContent({e}:{e:WorkElement}){
 const color=e.color||'#e66032';
 if(e.type==='image')return <img src={e.image} alt="Instruction photo" draggable={false} style={{width:'100%',height:'100%',objectFit:'fill',display:'block'}}/>;
 if(e.type==='text'||e.type==='table')return <div className="wi-rich" style={{width:'100%',height:'100%',padding:8,color,overflow:'hidden'}} dangerouslySetInnerHTML={{__html:e.html||''}}/>;
 if(e.type==='marker')return <div style={{borderRadius:'50%',background:color,color:'#fff',width:'100%',height:'100%',display:'flex',justifyContent:'center',alignItems:'center',fontSize:Math.min(e.w,e.h)*.5,fontWeight:700,border:'2px solid white',boxShadow:'0 1px 4px #0004'}}>{e.number}</div>;
 const w=Math.max(Math.abs(e.w),1),h=Math.max(Math.abs(e.h),1),pad=16;
 const x1=e.w<0?w:0,y1=e.h<0?h:0,x2=e.w<0?0:w,y2=e.h<0?0:h;
 const angle=Math.atan2(y2-y1,x2-x1),a=16;
 return <svg width={w+pad*2} height={h+pad*2} viewBox={`${-pad} ${-pad} ${w+pad*2} ${h+pad*2}`} style={{position:'absolute',left:-pad,top:-pad,overflow:'visible',pointerEvents:'none'}}>
 {e.type==='arrow'?<g stroke={color} strokeWidth="4" fill="none" strokeLinecap="round" strokeLinejoin="round"><path d={`M ${x1} ${y1} L ${x2} ${y2}`}/><path d={`M ${x2-a*Math.cos(angle-.5)} ${y2-a*Math.sin(angle-.5)} L ${x2} ${y2} L ${x2-a*Math.cos(angle+.5)} ${y2-a*Math.sin(angle+.5)}`}/></g>:e.type==='circle'?<ellipse cx={w/2} cy={h/2} rx={w/2} ry={h/2} stroke={color} strokeWidth="4" fill="none"/>:<rect width={w} height={h} stroke={e.type==='highlight'?'none':color} strokeWidth="4" fill={e.type==='highlight'?color:'none'} fillOpacity={e.type==='highlight'?.32:1}/>}
 </svg>;
}
export function CanvasContent({step}:{step:any}){return <div style={{position:'relative',width:PAGE_W,height:Math.max(180,...(step.elements||[]).map((e:WorkElement)=>Math.max(e.y,e.y+e.h)+20)),background:'#fff'}}>{(step.elements||[]).map((e:WorkElement)=><div key={e.id} style={{position:'absolute',left:Math.min(e.x,e.x+e.w),top:Math.min(e.y,e.y+e.h),width:Math.max(1,Math.abs(e.w)),height:Math.max(1,Math.abs(e.h))}}><ElementContent e={e}/></div>)}</div>}
export function StepBody({step}:{step:any}){const markers=(step.elements||[]).filter((e:WorkElement)=>e.type==='marker').sort((a:WorkElement,b:WorkElement)=>(a.number||0)-(b.number||0));return <div className="wi-print" style={{width:PAGE_W,background:'#fff'}}>
 {step.type==='text'?<div className="wi-rich" style={{padding:24,minHeight:180}} dangerouslySetInnerHTML={{__html:step.bodyHtml||''}}/>:<><CanvasContent step={step}/>{markers.length>0&&<div style={{padding:'16px 24px',borderTop:'1px solid #dbe2ed'}}>{markers.map((e:WorkElement)=><div key={e.id} style={{display:'flex',gap:12,marginBottom:12}}><strong style={{color:e.color,minWidth:24}}>{e.number}.</strong><span style={{whiteSpace:'pre-wrap'}}>{e.note||'Add an instruction for this marker.'}</span></div>)}</div>}{step.notesHtml&&<div className="wi-rich" style={{padding:24,borderTop:'1px solid #dbe2ed'}} dangerouslySetInnerHTML={{__html:step.notesHtml}}/>}</>}
 </div>}
