'use client';
import {useEffect,useRef,useState} from 'react';
import {Toaster,toast} from 'sonner';
import {Save,Download,Eye,Undo2,Redo2,Plus,Camera,ImagePlus,FileText,Settings2,FolderOpen,ArrowLeft,ArrowRight,Copy,Trash2,CloudUpload} from 'lucide-react';
import {instructionFilename} from '@/lib/instruction-filename';
import {makePDF} from '@/lib/pdf';
import {operationNames,validOperationName,memberOperations} from '@/lib/operations';
import {newDocument,newStep,upgradeDocument,id,loadImage,PAGE_W,PAGE_H,WorkElement} from '@/lib/work-layout';
import {StepBody,printCSS} from '@/components/work/page-view';
import CanvasEditor from '@/components/work/canvas-editor';
import RichText from '@/components/work/rich-text';
import Preview from '@/components/work/preview';
async function api(url:string,options?:RequestInit){const r=await fetch(url,options);let j:any;try{j=await r.json();}catch{throw new Error('Your session may have expired. Refresh the page to sign in again.');}if(!r.ok)throw new Error(j.error||'Unable to complete request.');return j;}
export default function Editor(){
 const [data,setData]=useState<any>(null),[doc,setDoc]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[index,setIndex]=useState(0),[tab,setTab]=useState('editor'),[preview,setPreview]=useState(false),[details,setDetails]=useState(true),[settings,setSettings]=useState(false),[config,setConfig]=useState<any>(null),[selected,setSelected]=useState<string|null>(null),[newOperation,setNewOperation]=useState(''),[historyTick,setHistoryTick]=useState(0);
 const history=useRef<any[]>([]),future=useRef<any[]>([]),live=useRef<any>(null),upload=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null),lastCheckpoint=useRef(0);live.current=doc;
 const step=doc?.steps[index],ops=operationNames(config||{}),allowedOps=data?.user?.admin?operationNames(data?.config||{}):(data?.user?.operations||[data?.user?.operation].filter(Boolean));
 async function run(fn:()=>Promise<void>){setBusy(true);try{await fn();}catch(e:any){toast.error(e.message,{duration:8000});}finally{setBusy(false);}}
 async function load(){try{const j=await api('/api/work');setData(j);setConfig(j.config);setDoc((old:any)=>old||newDocument(j.user.operation||'Laser'));setError('');}catch(e:any){setError(e.message);}}
 useEffect(()=>{load();},[]);
 useEffect(()=>{function prevent(e:BeforeUnloadEvent){if(dirty){e.preventDefault();e.returnValue='';}}window.addEventListener('beforeunload',prevent);return()=>window.removeEventListener('beforeunload',prevent);},[dirty]);
 function checkpoint(force=false){if(!live.current)return;const now=Date.now();if(!force&&now-lastCheckpoint.current<700)return;lastCheckpoint.current=now;history.current=[...history.current.slice(-39),structuredClone(live.current)];future.current=[];setHistoryTick(x=>x+1);}
 function change(next:any){setDoc(next);setDirty(true);}
 function changeStep(next:any){change({...live.current,steps:live.current.steps.map((s:any,i:number)=>i===index?next:s)});}
 function field(key:string,value:string){checkpoint();change({...doc,[key]:value});}
 function undo(redo=false){const src=redo?future:history,dst=redo?history:future;if(!src.current.length)return;dst.current.push(structuredClone(doc));const target=src.current.pop();setDoc({...target,version:doc.version,updated:doc.updated,driveId:doc.driveId});setIndex(Math.min(index,target.steps.length-1));setSelected(null);setDirty(true);setHistoryTick(x=>x+1);}
 async function save(){const j=await api('/api/work',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document:live.current})});setDoc(j.document);live.current=j.document;setDirty(false);setData((v:any)=>({...v,instructions:[j.document,...v.instructions.filter((x:any)=>x.id!==j.document.id)]}));return j.document;}
 async function pdf(drive=false){let current=live.current;const filename=instructionFilename(current);if(drive)current=await save();const p=await makePDF(current);if(drive){const f=new FormData();f.append('id',current.id);f.append('pdf',p.output('blob'),'instruction.pdf');const result=await api('/api/work',{method:'PUT',body:f});const synced={...live.current,driveId:result.driveId};live.current=synced;setDoc(synced);setData((v:any)=>({...v,instructions:v.instructions.map((d:any)=>d.id===synced.id?{...d,driveId:result.driveId}:d)}));toast.success('PDF saved to Google Drive. Future saves update this same file.');}else{p.save(filename);toast.success('Landscape PDF downloaded.');}}
 async function removeInstruction(target:any){
  const label=`${target.customerPart||target.knoedlerPart} / Rev ${target.customerRev||target.knoedlerRev||'—'} / ${target.operation}`;
  if(!confirm(`Delete instruction: ${label}?\n\nThis removes the instruction from the app and moves its linked PDF (if any) to Google Drive Trash. Unsaved edits to this instruction will be discarded.`))return;
  await run(async()=>{const result=await api('/api/work',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:target.id,version:target.version})});setData((v:any)=>({...v,instructions:v.instructions.filter((d:any)=>d.id!==target.id)}));if(live.current?.id===target.id){const next=newDocument(data.user.operation||'Laser');live.current=next;setDoc(next);setDirty(false);resetHistory();setPreview(false);setTab('library');}toast.success(result.driveTrashed?'Instruction deleted; linked PDF moved to Drive Trash.':'Instruction deleted.');});
 }
 function resetHistory(){history.current=[];future.current=[];setSelected(null);setIndex(0);setHistoryTick(x=>x+1);}
 function fresh(){if(dirty&&!confirm('Discard unsaved changes and start a new instruction?'))return;setDoc(newDocument(data.user.operation||'Laser'));setDirty(false);setTab('editor');setPreview(false);setDetails(true);resetHistory();}
 async function open(source:any){if(dirty&&!confirm('Discard unsaved changes and open this instruction?'))return;const next=await upgradeDocument(source);setDoc(next);setDirty(false);setTab('editor');setPreview(false);setDetails(false);resetHistory();}
 function add(type:string){checkpoint(true);change({...doc,steps:[...doc.steps,newStep(type)]});setIndex(doc.steps.length);setSelected(null);setPreview(false);}
 function reorder(direction:number){const target=index+direction;if(target<0||target>=doc.steps.length)return;checkpoint(true);const steps=[...doc.steps];[steps[index],steps[target]]=[steps[target],steps[index]];change({...doc,steps});setIndex(target);}
 function duplicateStep(){checkpoint(true);const clone=structuredClone(step),mapping=new Map<string,string>();clone.id=id();for(const e of clone.elements||[])mapping.set(e.id,id());clone.elements=(clone.elements||[]).map((e:WorkElement)=>({...e,id:mapping.get(e.id),parentId:e.parentId?mapping.get(e.parentId):undefined}));const steps=[...doc.steps];steps.splice(index+1,0,clone);change({...doc,steps});setIndex(index+1);setSelected(null);}
 async function addPhotos(files:File[]){if(!files.length)return;const instructionId=doc.id,stepId=step.id;checkpoint(true);for(const file of files){const form=new FormData();form.append('file',file);form.append('operation',doc.operation);const j=await api('/api/media',{method:'POST',body:form});const im=await loadImage(j.url);const w=Math.min(340,400*im.naturalWidth/im.naturalHeight),h=w*im.naturalHeight/im.naturalWidth;
  const current=live.current;if(current.id!==instructionId)return;const target=current.steps.find((s:any)=>s.id===stepId);const n=target.elements.filter((e:WorkElement)=>e.type==='image').length;const e={id:id(),type:'image',image:j.url,x:20+(n%3)*350,y:20+Math.floor(n/3)*410,w,h};const updated={...current,steps:current.steps.map((s:any)=>s.id===stepId?{...s,elements:[...s.elements,e],canvasHeight:Math.max(s.canvasHeight||PAGE_H,e.y+e.h+20)}:s)};live.current=updated;change(updated);setSelected(e.id);
 }toast.success(`${files.length} photo${files.length===1?'':'s'} added. Move and resize them on the page.`);}
 const activeUser=data?.user;
 return <><style>{printCSS}</style><Toaster richColors position="top-center"/><header className="app-header"><img className="company-logo" src="/knoedler-logo.png" alt="Knoedler Manufacturers Canada Ltée"/><div className="app-title"><strong>WORK INSTRUCTIONS</strong><small>Manufacturing workspace</small></div><div className="user-label"><strong>{activeUser?.admin?'Administrator':(activeUser?.operations?.length>1?'Multiple operations':activeUser?.operation)||'Workspace'}</strong><small>{activeUser?.email||'Sign-in required'}</small></div></header>
 <main className="app-main"><nav className="app-nav"><div className="nav-tabs"><button className={tab==='editor'?'active':''} onClick={()=>setTab('editor')}><FileText size={18}/>Editor</button><button className={tab==='library'?'active':''} onClick={()=>setTab('library')}><FolderOpen size={18}/>Instructions <span className="pill">{data?.instructions.length||0}</span></button></div>{activeUser?.admin&&<button onClick={()=>{setConfig(structuredClone(data.config));setSettings(true);}}><Settings2 size={18}/>Admin settings</button>}</nav>
 {error&&<div role="alert" className="error-banner">{error} <button onClick={()=>window.location.reload()}>Refresh / sign in</button><button onClick={load}>Retry</button></div>}
 {!doc&&!error&&<p className="loading">Loading your workspace…</p>}
 {doc&&tab==='editor'&&<><div className="document-bar"><div><div className="eyebrow">{doc.operation} / {dirty?'UNSAVED CHANGES':doc.version?'SAVED':'DRAFT'}</div><h1>{doc.knoedlerPart||'New work instruction'} <span>{doc.knoedlerRev?'Rev '+doc.knoedlerRev:''}</span></h1></div><div className="document-actions"><button disabled={busy||!doc.version} className="danger" onClick={()=>removeInstruction(doc)}><Trash2 size={18}/>Delete instruction</button><button disabled={busy} onClick={fresh}><Plus size={18}/>New</button><button disabled={busy} onClick={()=>setPreview(!preview)} className={preview?'active':''}><Eye size={18}/>{preview?'Edit':'Preview'}</button><button disabled={busy} onClick={()=>run(()=>pdf())}><Download size={18}/>PDF</button><button className="primary" disabled={busy||!data} onClick={()=>run(async()=>{await save();toast.success('Instruction saved.');})}><Save size={18}/>{busy?'Working…':'Save'}</button></div></div>
 <details className="part-details" open={details} onToggle={e=>setDetails(e.currentTarget.open)}><summary>Part details <span>{doc.description||'Add part numbers, revisions and description'}</span></summary><div className="part-grid">{[['customerPart','Customer Part #'],['customerRev','Customer Rev'],['knoedlerPart','Knoedler Part # *'],['knoedlerRev','Knoedler Rev']].map(([key,label])=><label key={key}>{label}<input disabled={busy||preview} value={doc[key]} onChange={e=>field(key,e.target.value)}/></label>)}<label className="description-field">Description *<textarea disabled={busy||preview} value={doc.description} onChange={e=>field('description',e.target.value)}/></label><label>Operation{allowedOps.length>1?<select disabled={busy||preview||doc.version>0} value={doc.operation} onChange={e=>{if(doc.steps.some((s:any)=>(s.elements||[]).some((x:WorkElement)=>x.type==='image'))){toast.error('Choose the operation before adding photos. Start a new instruction to use a different operation.');return;}field('operation',e.target.value);}}>{allowedOps.map((op:string)=><option key={op}>{op}</option>)}</select>:<input readOnly value={doc.operation}/>}<small>{activeUser?.admin&&doc.version>0?'Saved instructions retain their operation.':''}</small></label></div></details>
 <fieldset disabled={busy} className="editor-fieldset"><div className="step-strip">{doc.steps.map((s:any,i:number)=>{const photo=s.elements?.find((e:WorkElement)=>e.type==='image');return <button key={s.id} className={'step-thumb '+(index===i?'selected':'')} onClick={()=>{setIndex(i);setSelected(null);}}><span className="step-index">{String(i+1).padStart(2,'0')}</span><div className="thumb-picture">{photo?<img src={photo.image} alt=""/>:<FileText size={26}/>}</div><strong>{s.title||(s.type==='text'?'Text sheet':'Photo step')}</strong></button>;})}{!preview&&<div className="add-pages"><button onClick={()=>add('photo')}><ImagePlus size={18}/>Image step</button><button onClick={()=>add('text')}><FileText size={18}/>Text sheet</button></div>}</div>
 <section className="step-workspace"><div className="step-heading"><div><span className="eyebrow">STEP {index+1} OF {doc.steps.length}</span>{preview?<h2>{step.title||(step.type==='text'?'Text sheet':'Photo instruction')}</h2>:<input aria-label="Step title" placeholder={step.type==='text'?'Text sheet title':'Describe this step'} value={step.title} onChange={e=>{checkpoint();changeStep({...step,title:e.target.value});}}/>}</div><div className="step-controls">{!preview&&<><button aria-label="Undo edit" title="Undo edit" disabled={!history.current.length} onClick={()=>undo()}><Undo2 size={18}/></button><button aria-label="Redo edit" title="Redo edit" disabled={!future.current.length} onClick={()=>undo(true)}><Redo2 size={18}/></button><button aria-label="Move step earlier" disabled={index===0} onClick={()=>reorder(-1)}><ArrowLeft size={18}/></button><button aria-label="Move step later" disabled={index===doc.steps.length-1} onClick={()=>reorder(1)}><ArrowRight size={18}/></button><button aria-label="Duplicate step" onClick={duplicateStep}><Copy size={18}/></button><button aria-label="Delete step" disabled={doc.steps.length===1} onClick={()=>{if(confirm('Delete this step and its contents?')){checkpoint(true);change({...doc,steps:doc.steps.filter((_:any,i:number)=>i!==index)});setIndex(Math.max(0,index-1));setSelected(null);}}}><Trash2 size={18}/></button></>}</div></div>
 {preview?<Preview doc={doc} step={step}/>:step.type==='text'?<RichText key={step.id} value={step.bodyHtml||''} label="Text sheet content" onChange={html=>{checkpoint();changeStep({...step,bodyHtml:html});}}/>:<><div className="photo-upload-actions"><button onClick={()=>camera.current?.click()}><Camera size={18}/>Take photo</button><button onClick={()=>upload.current?.click()}><ImagePlus size={18}/>Add photos</button><span>Landscape layout · drag to arrange</span></div><input ref={upload} hidden type="file" accept="image/*" multiple onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';run(()=>addPhotos(files));}}/><input ref={camera} hidden type="file" accept="image/*" capture="environment" onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';run(()=>addPhotos(files));}}/>
 <CanvasEditor key={step.id} step={step} uploadPhoto={async(file)=>{const form=new FormData();form.append('file',file);form.append('operation',doc.operation);return (await api('/api/media',{method:'POST',body:form})).url;}} onChange={changeStep} onGestureStart={()=>checkpoint(true)} selected={selected} setSelected={setSelected}/>
 <details className="notes-section"><summary>Step notes and additional tables</summary><RichText key={step.id+'notes'} compact label="Step notes" value={step.notesHtml||''} onChange={html=>{checkpoint();changeStep({...step,notesHtml:html});}}/></details></>}
 </section></fieldset>
 <footer className="drive-bar"><div><strong>{data?.driveReady?'Google Drive configured':'Google Drive connection pending'}</strong><small>{data?.config?.folders?.[doc.operation]?`Destination: ${doc.operation} folder`:'Ask your administrator to assign a folder.'}</small></div><button className="primary" disabled={busy||!data?.driveReady||!data?.config?.folders?.[doc.operation]} onClick={()=>run(()=>pdf(true))}><CloudUpload size={18}/>Save PDF to Drive</button></footer></>}
 {tab==='library'&&<><div className="document-bar"><h1>Work instructions</h1><button disabled={!data||busy} className="primary" onClick={fresh}><Plus size={18}/>New instruction</button></div><div className="instruction-grid">{data?.instructions.map((d:any)=><div key={d.id} className="instruction-list-item"><button disabled={busy} className="instruction-card" onClick={()=>run(()=>open(d))}><span className="pill">{d.operation}</span><h2>{d.knoedlerPart}</h2><p>{d.description}</p><small>Rev {d.knoedlerRev||'—'} · {d.steps.length} steps</small><strong>Open instruction →</strong></button><button disabled={busy} className="danger instruction-delete" onClick={()=>removeInstruction(d)}><Trash2 size={16}/>Delete instruction</button></div>)}</div>{!data?.instructions.length&&<p className="empty-state">No instructions yet. Create your first instruction in the editor.</p>}</>}
 </main>
 {settings&&activeUser?.admin&&<div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-label="Workspace settings" className="settings-modal"><div className="modal-heading"><h2>Workspace settings</h2><button disabled={busy} onClick={()=>setSettings(false)}>Close</button></div><h3>Operations</h3><div className="operation-pills">{ops.map(op=><span key={op} className="pill">{op}</span>)}</div><div className="inline-form"><input placeholder="New operation name" value={newOperation} onChange={e=>setNewOperation(e.target.value)}/><button onClick={()=>{const name=newOperation.trim();if(!validOperationName(name)||ops.some(op=>op.toLowerCase()===name.toLowerCase())){toast.error('Enter a unique operation name without slashes.');return;}setConfig({...config,operations:[...ops,name]});setNewOperation('');}}>Add</button></div><h3>Google Drive folders</h3>{ops.map(op=><label className="folder-row" key={op}>{op}<input placeholder="Drive folder link or ID" value={config.folders?.[op]||''} onChange={e=>{const value=e.target.value;setConfig({...config,folders:{...config.folders,[op]:value.match(/folders\/([\w-]+)/)?.[1]||value}});}}/></label>)}<h3>Operation accounts</h3><p>Assign the full email used to sign in. Select all operations this account can create and edit.</p>{(config.members||[]).map((m:any,i:number)=><div className="account-row" key={i}><input aria-label="Account email" value={m.email} placeholder="name@knoedler.com" onChange={e=>setConfig({...config,members:config.members.map((x:any,k:number)=>k===i?{...x,email:e.target.value}:x)})}/><div className="account-operations">{ops.map(op=><label key={op}><input type="checkbox" checked={memberOperations(m).includes(op)} onChange={e=>{const operations=e.target.checked?[...memberOperations(m),op]:memberOperations(m).filter(x=>x!==op);setConfig({...config,members:config.members.map((x:any,k:number)=>k===i?{...x,operations}:x)});}}/>{op}</label>)}</div><button aria-label="Remove account" onClick={()=>setConfig({...config,members:config.members.filter((_:any,k:number)=>k!==i)})}><Trash2 size={17}/></button></div>)}<button onClick={()=>setConfig({...config,members:[...(config.members||[]),{email:'',operations:['Laser']}]})}>+ Add account</button><button className="primary save-settings" disabled={busy} onClick={()=>run(async()=>{await api('/api/work',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'config',config})});setData({...data,config});setSettings(false);toast.success('Settings saved.');})}>Save settings</button></section></div>}
 </>;
}
