'use client';
import {useState,useEffect,useRef} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableCell,TableRow} from '@/components/ui/table';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Toaster,toast} from 'sonner';
import {Plus,Save,Download,FolderOpen,Settings2,Camera,Upload,ArrowUpRight,Square,Circle,Highlighter,Type,Undo2,Trash2,FileText,ChevronRight,Layers,ArrowUp,ArrowDown,CloudUpload,Check,PenLine,ImagePlus} from 'lucide-react';
import {makePDF} from '@/lib/pdf';
import {stepPhotos} from '@/lib/photos';
import {operationNames,validOperationName} from '@/lib/operations';
const uid=()=>crypto.randomUUID();
const step=(type='photo')=>({id:uid(),type,title:'',notes:'',photos:[] as any[],tables:[] as string[][][]});
const blank=(op='Laser')=>({id:uid(),customerPart:'',customerRev:'',knoedlerPart:'',knoedlerRev:'',description:'',operation:op,version:0,steps:[step()]});
async function api(url:string,options?:RequestInit){const r=await fetch(url,options);const j:any=await r.json();if(!r.ok)throw new Error(j.error||'Unable to complete request.');return j;}
function Choice({value,onChange,items}:any){return <Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{items.map((x:string)=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select>}
export default function Editor(){
 const [d,setD]=useState<any>(null),[data,setData]=useState<any>(null),[error,setError]=useState(''),[tab,setTab]=useState('editor'),[index,setIndex]=useState(0),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[tool,setTool]=useState('arrow'),[color,setColor]=useState('#ed5e35'),[label,setLabel]=useState(''),[draft,setDraft]=useState<any>(null),[settings,setSettings]=useState(false),[config,setConfig]=useState<any>(null),[preview,setPreview]=useState(false),[photoIndex,setPhotoIndex]=useState(0),[newOperation,setNewOperation]=useState('');
 const upload=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null),replacement=useRef<HTMLInputElement>(null);const s=d?.steps[index];const photos=s?stepPhotos(s):[];const activePhoto=photos[photoIndex]||photos[0];const ops=operationNames(data?.config||{});const settingOps=operationNames(config||{});
 useEffect(()=>{setPhotoIndex(0);setDraft(null)},[index,d?.id]);
 async function load(){try{const j=await api('/api/work');setData(j);setConfig(j.config);setD((prev:any)=>prev||blank(j.user.operation||'Laser'));setError('');}catch(e:any){setError(e.message);setD((prev:any)=>prev||blank());}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f)},[dirty]);
 const update=(p:any)=>{setD((v:any)=>({...v,...p}));setDirty(true)};
 const editStep=(p:any)=>update({steps:d.steps.map((x:any,i:number)=>i===index?{...x,...p}:x)});
 async function save(){const j=await api('/api/work',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document:d})});setD(j.document);setDirty(false);setData((v:any)=>({...v,instructions:[j.document,...(v?.instructions||[]).filter((x:any)=>x.id!==d.id)]}));return j.document;}
 async function run(f:()=>Promise<any>){setBusy(true);try{await f()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 async function exportPDF(drive=false){let doc=d;if(drive)doc=await save();const p=await makePDF(doc);if(drive){const f=new FormData();f.append('id',doc.id);f.append('pdf',p.output('blob'),`${doc.knoedlerPart}.pdf`);await api('/api/work',{method:'PUT',body:f});toast.success('PDF saved to Google Drive.');}else{p.save(`${doc.knoedlerPart||'Work-instruction'}_Rev-${doc.knoedlerRev||'NA'}_${doc.operation}.pdf`);toast.success('PDF downloaded.')}}
 async function photo(files:File[],replaceId?:string){if(!files.length)return;const stepId=s.id;const docId=d.id;const operation=d.operation;await run(async()=>{let added=0;for(const file of files){const f=new FormData();f.append('file',file);f.append('operation',operation);const j=await api('/api/media',{method:'POST',body:f});const item={id:uid(),image:j.url,annotations:[]};setD((current:any)=>current.id!==docId?current:{...current,steps:current.steps.map((st:any)=>st.id===stepId?{...st,photos:replaceId?stepPhotos(st).map((ph:any)=>ph.id===replaceId?{...item,id:replaceId}:ph):[...stepPhotos(st),item],image:undefined,annotations:undefined}:st)});setDirty(true);added++;}toast.success(`${added} photo${added===1?'':'s'} added.`);});}
 function editPhoto(p:any){if(!activePhoto)return;editStep({photos:photos.map((ph:any)=>ph.id===activePhoto.id?{...ph,...p}:ph),image:undefined,annotations:undefined});}
 function removePhoto(){if(!confirm('Remove this photo and its annotations?'))return;editStep({photos:photos.filter((ph:any)=>ph.id!==activePhoto.id),image:undefined,annotations:undefined});setPhotoIndex(0);setDraft(null);}
 function startNew(){if(dirty&&!confirm('Discard unsaved changes and start a new instruction?'))return;setD(blank(data?.user.operation||d.operation));setIndex(0);setDirty(false);setTab('editor')}
 function point(e:any){const r=e.currentTarget.getBoundingClientRect();return {x:Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)),y:Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100))}}
 function down(e:any){if(preview)return;e.currentTarget.setPointerCapture(e.pointerId);const p=point(e);if(tool==='text'){if(!label.trim()){toast.error('Enter your photo label first.');return;}editPhoto({annotations:[...activePhoto.annotations,{...p,x2:p.x,y2:p.y,type:'text',text:label,color}]});return;}setDraft({...p,x2:p.x,y2:p.y,type:tool,color});}
 function finish(e:any){if(!draft)return;const p=point(e);if(Math.abs(p.x-draft.x)+Math.abs(p.y-draft.y)>1)editPhoto({annotations:[...activePhoto.annotations,{...draft,x2:p.x,y2:p.y}]});setDraft(null)}
 function annotation(a:any,i:number){const props={stroke:a.color,strokeWidth:.5,fill:'none'};if(a.type==='arrow'){const angle=Math.atan2(a.y2-a.y,a.x2-a.x);return <g key={i} {...props}><line x1={a.x} y1={a.y} x2={a.x2} y2={a.y2}/><path d={`M ${a.x2-2*Math.cos(angle-.5)} ${a.y2-2*Math.sin(angle-.5)} L ${a.x2} ${a.y2} L ${a.x2-2*Math.cos(angle+.5)} ${a.y2-2*Math.sin(angle+.5)}`}/></g>}if(a.type==='text')return <text key={i} x={a.x} y={a.y} fill={a.color} fontSize="3" fontWeight="700">{a.text}</text>;if(a.type==='circle')return <ellipse key={i} cx={(a.x+a.x2)/2} cy={(a.y+a.y2)/2} rx={Math.abs(a.x2-a.x)/2} ry={Math.abs(a.y2-a.y)/2} {...props}/>;return <rect key={i} x={Math.min(a.x,a.x2)} y={Math.min(a.y,a.y2)} width={Math.abs(a.x2-a.x)} height={Math.abs(a.y2-a.y)} {...props} fill={a.type==='highlight'?a.color:'none'} fillOpacity={.3}/>}
 useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const abort=new AbortController();Promise.resolve(mc.registerTool({name:'read_current_instruction',description:'Read the currently open work instruction without changing or saving it.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:any)=>{if(input&&Object.keys(input).length)throw new Error('No parameters accepted');return d;}},{signal:abort.signal})).catch(()=>{});return()=>abort.abort()},[d]);
 if(!d)return <main className="loading">Opening your work instructions…</main>;
 return <><Toaster richColors position="bottom-right"/><header className="topbar"><div className="brand"><span className="brandmark">K</span><div>KNOEDLER<small>MANUFACTURING WORKSPACE</small></div></div><span className="topcaption">Work Instructions</span><div className="identity"><span className="avatar">{data?.user.admin?'RT':d.operation.slice(0,2)}</span><div>{data?.user.admin?'Administrator':data?.user.operation||'Workspace'}<small>{data?.user.email||'Sign-in required'}</small></div></div></header>
 <main><Tabs value={tab} onValueChange={setTab}><div className="navrow"><TabsList><TabsTrigger value="editor"><PenLine size={16}/> Editor</TabsTrigger><TabsTrigger value="library"><FolderOpen size={16}/> Instructions <span className="count">{data?.instructions.length||0}</span></TabsTrigger></TabsList>{data?.user.admin&&<Button variant="ghost" onClick={()=>setSettings(true)}><Settings2/> Admin settings</Button>}</div>
 {error&&<div className="notice error">{error} <a href="/cdn-cgi/access/login" target="_top">Sign in</a> <Button variant="outline" onClick={load}>Retry</Button></div>}
 <TabsContent value="editor"><div className="heading"><div><div className="eyebrow">WORK INSTRUCTION / {d.operation.toUpperCase()}</div><h1>{d.knoedlerPart||'New work instruction'}</h1><p className="muted">{dirty?'Unsaved changes':d.version?`Saved · Version ${d.version}`:'Start with the part details, then build your steps.'}</p></div><div className="actions"><Button variant="outline" onClick={startNew}><Plus/> New</Button><Button variant="outline" disabled={busy} onClick={()=>run(()=>exportPDF())}><Download/> PDF</Button><Button disabled={busy||!data} onClick={()=>run(async()=>{await save();toast.success('Instruction saved.');})}><Save/> {busy?'Working…':'Save instruction'}</Button></div></div>
 <section className="panel details"><div className="sectiontitle"><span className="squareicon"><FileText size={18}/></span><h2>Part details</h2><span className="badge">{d.operation}</span></div><div className="fields">{[['customerPart','Customer Part #'],['customerRev','Customer Rev'],['knoedlerPart','Knoedler Part # *'],['knoedlerRev','Knoedler Rev']].map(([key,title])=><label key={key}>{title}<Input value={d[key]} onChange={e=>update({[key]:e.target.value})} placeholder={key.includes('Rev')?'e.g. A':'Enter part number'} readOnly={preview}/></label>)}<label className="description">Description *<Input value={d.description} placeholder="Describe the part or assembly" onChange={e=>update({description:e.target.value})} readOnly={preview}/></label><label>Operation{data?.user.admin&&!d.version&&!d.steps.some((x:any)=>stepPhotos(x).length)?<Choice value={d.operation} onChange={(v:string)=>update({operation:v})} items={ops}/>:<Input value={d.operation} readOnly/>}{data?.user.admin&&<Button size="sm" variant="link" onClick={()=>setSettings(true)}>+ Add operation</Button>}</label></div></section>
 <div className="workspace"><aside className="steps"><div className="sectiontitle"><h2>Steps</h2><span className="count">{d.steps.length}</span></div>{d.steps.map((x:any,i:number)=><button key={x.id} className={'stepitem '+(index===i?'selected':'')} onClick={()=>setIndex(i)}><span className="stepnum">{String(i+1).padStart(2,'0')}</span><span>{x.title||(x.type==='text'?'Untitled text sheet':'Untitled step')}<small>{x.type==='text'?'Text sheet':stepPhotos(x).length?`${stepPhotos(x).length} photos`:'No photo yet'}</small></span><ChevronRight size={16}/></button>)}{!preview&&<><Button className="addstep" variant="outline" onClick={()=>{update({steps:[...d.steps,step()]});setIndex(d.steps.length)}}><Plus/> Add step</Button><Button className="addstep" variant="outline" onClick={()=>{update({steps:[...d.steps,step('text')]});setIndex(d.steps.length)}}><FileText/> Add text sheet</Button></>}<div className="stepfoot"><Layers size={18}/><p>One clear action per step.<br/>Add a photo to show the detail.</p></div></aside>
 <section className="panel stepeditor"><div className="stephead"><div><span className="eyebrow">{s.type==='text'?'TEXT SHEET':'STEP'} {String(index+1).padStart(2,'0')}</span><h2>{s.title||(s.type==='text'?'Write your text sheet':'Build this step')}</h2></div><Button variant="outline" onClick={()=>setPreview(!preview)}>{preview?'Edit':'Preview'}</Button></div>
 {!preview&&<label className="steptitle">{s.type==='text'?'Sheet title':'Step title'}<Input value={s.title} placeholder={s.type==='text'?'e.g. Safety precautions and general requirements':'e.g. Position the part in the fixture'} onChange={e=>editStep({title:e.target.value})}/></label>}
 {s.type!=='text'&&<><div className="photomanager"><div className="sectiontitle"><h3>Photos</h3><span className="count">{photos.length}</span>{!preview&&<div className="actions"><Button variant="outline" size="sm" disabled={busy||!data} onClick={()=>camera.current?.click()}><Camera/> Take photo</Button><Button variant="outline" size="sm" disabled={busy||!data} onClick={()=>upload.current?.click()}><Plus/> Add photos</Button></div>}</div>{photos.length>0&&!preview&&<div className="photothumbs">{photos.map((ph:any,i:number)=><button key={ph.id} className={activePhoto.id===ph.id?'selected':''} aria-label={`Edit photo ${i+1}`} aria-pressed={activePhoto.id===ph.id} onClick={()=>{setPhotoIndex(i);setDraft(null)}}><img src={ph.image} alt={`Photo ${i+1}`}/><span>Photo {i+1}</span></button>)}</div>}</div>
 {preview&&photos.length>0?<div className="previewphotos">{photos.map((ph:any,i:number)=><div key={ph.id}><div className="imagecanvas"><img src={ph.image} alt={`Photo ${i+1}: ${s.title}`}/><svg viewBox="0 0 100 100" preserveAspectRatio="none">{ph.annotations.map(annotation)}</svg></div><small>Photo {i+1}</small></div>)}</div>:<div className="photoarea">{activePhoto?<><div className="imagecanvas"><img src={activePhoto.image} alt={s.title||'Instruction photo'}/><svg viewBox="0 0 100 100" preserveAspectRatio="none" onPointerDown={down} onPointerMove={e=>draft&&setDraft({...draft,x2:point(e).x,y2:point(e).y})} onPointerUp={finish} onPointerCancel={()=>setDraft(null)}>{activePhoto.annotations.map(annotation)}{draft&&annotation(draft,-1)}</svg></div>{!preview&&<div className="photoreplace actions"><Button size="sm" variant="outline" disabled={busy} onClick={()=>replacement.current?.click()}><Upload/> Replace photo</Button><Button size="sm" variant="outline" onClick={removePhoto}><Trash2/> Remove photo</Button></div>}</>:<div className="photoempty"><span><ImagePlus size={32}/></span><h3>Show how it’s done</h3><p>Add multiple photos to this step.<br/>Select a photo to add arrows, highlights and notes.</p><div className="actions"><Button variant="outline" disabled={busy||!data} onClick={()=>camera.current?.click()}><Camera/> Take photo</Button><Button disabled={busy||!data} onClick={()=>upload.current?.click()}><Upload/> Upload photos</Button></div><small>JPG, PNG or WebP · up to 12 MB per photo</small></div>}</div>}
 <input type="file" accept="image/jpeg,image/png,image/webp" hidden ref={replacement} onChange={e=>{photo(Array.from(e.target.files||[]),activePhoto?.id);e.target.value=''}}/><input type="file" accept="image/jpeg,image/png,image/webp" multiple hidden ref={upload} onChange={e=>{photo(Array.from(e.target.files||[]));e.target.value=''}}/><input type="file" accept="image/*" capture="environment" hidden ref={camera} onChange={e=>{photo(Array.from(e.target.files||[]));e.target.value=''}}/>
 {!preview&&<div className="annotationbar"><span className="toolcaption">ANNOTATE PHOTO {activePhoto?photos.indexOf(activePhoto)+1:''}</span>{[['arrow',ArrowUpRight,'Arrow'],['rectangle',Square,'Box'],['circle',Circle,'Circle'],['highlight',Highlighter,'Highlight'],['text',Type,'Text']].map(([value,Icon,title]:any)=><Button key={value} title={title} aria-label={title} variant={tool===value?'secondary':'ghost'} className={tool===value?'activeTool':''} disabled={!activePhoto} onClick={()=>setTool(value)}><Icon size={18}/><span>{title}</span></Button>)}<input aria-label="Annotation colour" type="color" value={color} onChange={e=>setColor(e.target.value)}/><Button variant="ghost" aria-label="Undo last annotation" disabled={!activePhoto?.annotations.length} onClick={()=>editPhoto({annotations:activePhoto.annotations.slice(0,-1)})}><Undo2/></Button>{tool==='text'&&<Input className="textlabel" placeholder="Photo label; tap photo to place" value={label} onChange={e=>setLabel(e.target.value)}/>}</div>}
 </>}
 <div className={s.type==='text'?'notes textsheet':'notes'}><label>{s.type==='text'?'Sheet content':'Instructions & notes'}{preview?<p className="readnotes">{s.notes||'No notes added.'}</p>:<Textarea rows={s.type==='text'?16:4} placeholder={s.type==='text'?'Write or paste your instructions here. Use separate lines for paragraphs, numbered instructions or checklists.':'Explain what to do, what to check, and any precautions…'} value={s.notes} onChange={e=>editStep({notes:e.target.value})}/>}</label></div>
 {s.tables.map((table:string[][],ti:number)=><div className="editabletable" key={ti}><Table><TableBody>{table.map((row,ri)=><TableRow key={ri}>{row.map((cell,ci)=><TableCell key={ci}>{preview?cell:<Input aria-label={`Table ${ti+1}, row ${ri+1}, column ${ci+1}`} value={cell} placeholder={ri===0?'Heading':'Value'} onChange={e=>editStep({tables:s.tables.map((t:any,k:number)=>k!==ti?t:t.map((r:any,a:number)=>a!==ri?r:r.map((v:any,b:number)=>b===ci?e.target.value:v)))})}/>}</TableCell>)}{!preview&&<TableCell><Button variant="ghost" aria-label="Delete row" disabled={table.length<2} onClick={()=>editStep({tables:s.tables.map((t:any,k:number)=>k===ti?t.filter((_:any,r:number)=>r!==ri):t)})}><Trash2 size={14}/></Button></TableCell>}</TableRow>)}</TableBody></Table>{!preview&&<div className="actions"><Button variant="outline" size="sm" onClick={()=>editStep({tables:s.tables.map((t:any,k:number)=>k===ti?[...t,Array(t[0].length).fill('')]:t)})}>+ Row</Button><Button variant="outline" size="sm" disabled={table[0].length>=8} onClick={()=>editStep({tables:s.tables.map((t:any,k:number)=>k===ti?t.map((r:any)=>[...r,'']):t)})}>+ Column</Button><Button variant="ghost" size="sm" disabled={table[0].length<2} onClick={()=>editStep({tables:s.tables.map((t:any,k:number)=>k===ti?t.map((r:any)=>r.slice(0,-1)):t)})}>Remove last column</Button><Button variant="ghost" size="sm" onClick={()=>confirm('Delete this table?')&&editStep({tables:s.tables.filter((_:any,k:number)=>k!==ti)})}>Delete table</Button></div>}</div>)}
 {!preview&&<div className="stepactions"><Button variant="outline" onClick={()=>editStep({tables:[...s.tables,[['Checkpoint','Requirement','Method'],['','','']]]})}><Plus/> Add table</Button><div className="actions"><Button title="Move step up" aria-label="Move step up" variant="ghost" disabled={index===0} onClick={()=>{const a=[...d.steps];[a[index],a[index-1]]=[a[index-1],a[index]];update({steps:a});setIndex(index-1)}}><ArrowUp/></Button><Button title="Move step down" aria-label="Move step down" variant="ghost" disabled={index===d.steps.length-1} onClick={()=>{const a=[...d.steps];[a[index],a[index+1]]=[a[index+1],a[index]];update({steps:a});setIndex(index+1)}}><ArrowDown/></Button><Button variant="ghost" disabled={d.steps.length===1} onClick={()=>{if(confirm('Delete this sheet or step and its contents?')){update({steps:d.steps.filter((_:any,i:number)=>i!==index)});setIndex(Math.max(0,index-1));}}}><Trash2/> Delete {s.type==='text'?'sheet':'step'}</Button></div></div>}
 </section></div><div className="savebar"><div><CloudUpload size={20}/><span>{data?.driveReady?'Google Drive connected':'Google Drive connection pending'}<small>{data?.config.folders[d.operation]?'Destination configured for '+d.operation:'Admin can assign a destination folder in settings.'}</small></span></div><Button variant="outline" disabled={busy||!data?.driveReady||!data?.config.folders[d.operation]} onClick={()=>run(()=>exportPDF(true))}><CloudUpload/> Save PDF to Drive</Button></div></TabsContent>
 <TabsContent value="library"><div className="heading"><div><div className="eyebrow">YOUR WORKSPACE</div><h1>Work instructions</h1><p className="muted">Open a saved instruction to continue editing.</p></div><Button onClick={startNew}><Plus/> New instruction</Button></div>{!data?.instructions.length?<section className="panel emptylibrary"><FolderOpen size={36}/><h2>No saved instructions yet</h2><p>Create your first instruction in the editor.</p><Button onClick={()=>setTab('editor')}>Open editor</Button></section>:<div className="librarygrid">{data.instructions.map((x:any)=><button className="panel librarycard" key={x.id} onClick={()=>{if(dirty&&!confirm('Discard unsaved changes and open this instruction?'))return;setD(x);setIndex(0);setDirty(false);setTab('editor')}}><span className="badge">{x.operation}</span><h2>{x.knoedlerPart}</h2><p>{x.description}</p><footer>Rev {x.knoedlerRev||'—'} · {x.steps.length} steps <span>Open <ChevronRight size={16}/></span></footer></button>)}</div>}</TabsContent></Tabs></main>
 <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="settingsdialog"><DialogHeader><DialogTitle>Workspace settings</DialogTitle><DialogDescription>Assign each operation’s folder and account. Only administrators can change these settings.</DialogDescription></DialogHeader><h3>Operations</h3><p className="muted">Add your own operation names, then save settings.</p><div className="operationchips">{settingOps.map(op=><span className="badge" key={op}>{op}</span>)}</div><div className="actions"><Input aria-label="New operation name" placeholder="e.g. Inspection or Packaging" value={newOperation} maxLength={80} onChange={e=>setNewOperation(e.target.value)}/><Button variant="outline" onClick={()=>{const name=newOperation.trim();if(!validOperationName(name)){toast.error('Enter a name without slashes (up to 80 characters).');return;}if(settingOps.some(op=>op.toLowerCase()===name.toLowerCase())){toast.error('That operation already exists.');return;}setConfig({...config,operations:[...settingOps,name]});setNewOperation('');}}><Plus/> Add operation</Button></div><h3>Google Drive folders</h3><p className="muted">Paste a folder link or ID for each operation.</p>{settingOps.map(op=><label className="settingrow" key={op}>{op}<Input placeholder="Google Drive folder link or ID" value={config?.folders[op]||''} onChange={e=>{const v=e.target.value;const id=v.match(/folders\/([\w-]+)/)?.[1]||v;setConfig({...config,folders:{...config.folders,[op]:id}})}}/></label>)}<div className="notice">{data?.driveReady?'Google Drive is connected.':'Drive is not connected yet. A one-time Google authorization must be configured before PDFs can upload. PDF download and instruction saving work independently.'}</div><h3>Operation accounts</h3><p className="muted">Use the email each person signs in with. Also allow these email addresses in your Cloudflare Access policy.</p>{config?.members.map((m:any,i:number)=><div className="memberrow" key={i}><Input aria-label="Account email" placeholder="department@knoedler.com" value={m.email} onChange={e=>setConfig({...config,members:config.members.map((x:any,k:number)=>k===i?{...x,email:e.target.value}:x)})}/><Choice value={m.operation} items={settingOps} onChange={(v:string)=>setConfig({...config,members:config.members.map((x:any,k:number)=>k===i?{...x,operation:v}:x)})}/><Button variant="ghost" aria-label="Remove account" onClick={()=>setConfig({...config,members:config.members.filter((_:any,k:number)=>k!==i)})}><Trash2/></Button></div>)}<Button variant="outline" onClick={()=>setConfig({...config,members:[...config.members,{email:'',operation:'Laser'}]})}><Plus/> Add account</Button><Button disabled={busy} onClick={()=>run(async()=>{await api('/api/work',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'config',config})});setData({...data,config});setSettings(false);toast.success('Workspace settings saved.');})}><Check/> Save settings</Button></DialogContent></Dialog>
 </>;
}
