import {operationNames,addOperations} from '@/lib/operations';
import {context,db,writable,sameOrigin,failure,driveReady,driveToken} from '@/lib/server';
export async function GET(){try{const c=await context();const q=c.admin?db().prepare('SELECT * FROM instructions ORDER BY updated DESC'):db().prepare('SELECT * FROM instructions WHERE operation=? ORDER BY updated DESC').bind(c.operation);const rows=await q.all();return Response.json({user:{email:c.user.email,admin:c.admin,operation:c.operation},config:c.admin?c.config:{folders:{[c.operation]:c.config.folders[c.operation]}},driveReady:driveReady(),instructions:rows.results.map((r:any)=>({...JSON.parse(r.data),version:r.version,updated:r.updated,driveId:r.drive_id}))});}catch(e){return failure(e);}}
export async function POST(req:Request){try{sameOrigin(req);const c=await context();const b:any=await req.json();
 if(b.action==='config'){if(!c.admin)throw new Error('Administrator access required.');const {folders,members}=b.config;const operations=addOperations(operationNames(c.config),b.config.operations||[]);if(!members.every((m:any)=>typeof m.email==='string'&&m.email.includes('@')&&operations.includes(m.operation)))throw new Error('Enter a valid email and operation for each account.');if(new Set(members.map((m:any)=>m.email.toLowerCase())).size!==members.length)throw new Error('Each email can have only one operation.');for(const v of Object.values(folders))if(v&&!/^[a-zA-Z0-9_-]+$/.test(v as string))throw new Error('Use a Google Drive folder ID or paste its folder link.');const config={...c.config,folders,members,operations};await db().prepare('UPDATE settings SET value=? WHERE id=?').bind(JSON.stringify(config),'config').run();return Response.json({ok:true});}
 const d=b.document;writable(c,d.operation);if(!d.id||!d.knoedlerPart?.trim()||!d.description?.trim())throw new Error('Knoedler Part # and Description are required.');if(JSON.stringify(d).length>1000000)throw new Error('This instruction is too large. Use fewer steps or smaller tables.');
 const old:any=await db().prepare('SELECT * FROM instructions WHERE id=?').bind(d.id).first();if(old){writable(c,old.operation);if(d.version!==old.version)throw new Error('Someone has updated this instruction. Download your PDF to keep your changes, then reopen the latest version.');}
 const updated=new Date().toISOString();const version=(old?.version||0)+1;const data=JSON.stringify({...d,version,updated});
 if(old){const r=await db().prepare('UPDATE instructions SET data=?,operation=?,version=?,updated=? WHERE id=? AND version=?').bind(data,d.operation,version,updated,d.id,old.version).run();if(!r.meta.changes)throw new Error('Another user saved first. Reopen the latest version before updating.');}else{await db().prepare('INSERT INTO instructions(id,operation,data,version,updated) VALUES(?,?,?,?,?)').bind(d.id,d.operation,data,version,updated).run();}
 await db().prepare('INSERT INTO revisions(id,instruction_id,data,version,updated) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),d.id,data,version,updated).run();return Response.json({document:{...d,version,updated,driveId:old?.drive_id}});
 }catch(e){return failure(e);}}
export async function PUT(req:Request){try{sameOrigin(req);const c=await context();const f=await req.formData();const id=String(f.get('id'));const row:any=await db().prepare('SELECT * FROM instructions WHERE id=?').bind(id).first();if(!row)throw new Error('Save the instruction before exporting.');writable(c,row.operation);const folder=c.config.folders[row.operation];if(!folder)throw new Error('Your administrator needs to assign a Google Drive folder for this operation.');const pdf=f.get('pdf') as File;if(!pdf||pdf.type!=='application/pdf'||pdf.size>25000000)throw new Error('Upload a PDF smaller than 25 MB.');const token=await driveToken();const d=JSON.parse(row.data);const name=`${d.knoedlerPart}_Rev-${d.knoedlerRev||'NA'}_${d.operation}.pdf`.replace(/[\\/]/g,'-');const metadata:any={name,mimeType:'application/pdf'};if(!row.drive_id)metadata.parents=[folder];const boundary='wi_'+crypto.randomUUID();const payload=new Blob([`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: application/pdf\r\n\r\n`,pdf,`\r\n--${boundary}--`]);
 const r=await fetch(`https://www.googleapis.com/upload/drive/v3/files${row.drive_id?'/'+encodeURIComponent(row.drive_id):''}?uploadType=multipart&supportsAllDrives=true&fields=id,webViewLink`,{method:row.drive_id?'PATCH':'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':`multipart/related; boundary=${boundary}`},body:payload});if(!r.ok)throw new Error('Google Drive could not save this PDF. Check folder access and reconnect if needed.');const j:any=await r.json();await db().prepare('UPDATE instructions SET drive_id=? WHERE id=?').bind(j.id,id).run();return Response.json({ok:true,url:j.webViewLink||`https://drive.google.com/file/d/${j.id}/view`});}catch(e){return failure(e);}}
