import {deleteInstruction} from '@/lib/delete-instruction';
import {instructionFilename} from '@/lib/instruction-filename';
import {saveDrivePDF} from '@/lib/drive-pdf';
import {operationNames,addOperations,memberOperations} from '@/lib/operations';
import {context,db,writable,sameOrigin,failure,driveReady,driveToken} from '@/lib/server';
export async function GET(){try{const c=await context();const q=c.admin?db().prepare("SELECT * FROM instructions WHERE COALESCE(json_extract(data,'$.deleted'),0)=0 ORDER BY updated DESC"):db().prepare(`SELECT * FROM instructions WHERE COALESCE(json_extract(data,'$.deleted'),0)=0 AND operation IN (${c.operations.map(()=>'?').join(',')}) ORDER BY updated DESC`).bind(...c.operations);const rows=await q.all();return Response.json({user:{email:c.user.email,admin:c.admin,operation:c.operation,operations:c.operations},config:c.admin?{...c.config,members:(c.config.members||[]).map((m:any)=>({...m,operations:memberOperations(m)}))}:{operations:c.operations,folders:Object.fromEntries(c.operations.map(op=>[op,c.config.folders[op]]))},driveReady:driveReady(),instructions:rows.results.map((r:any)=>({...JSON.parse(r.data),version:r.version,updated:r.updated,driveId:r.drive_id}))});}catch(e){return failure(e);}}
export async function POST(req:Request){try{sameOrigin(req);const c=await context();const b:any=await req.json();
 if(b.action==='config'){if(!c.admin)throw new Error('Administrator access required.');const {folders}=b.config;if(!Array.isArray(b.config.members)||!folders||typeof folders!=='object')throw new Error('Invalid settings.');const members=b.config.members.map((m:any)=>({email:String(m.email||'').trim().toLowerCase(),operations:Array.from(new Set(memberOperations(m)))}));const operations=addOperations(operationNames(c.config),b.config.operations||[]);if(!members.every((m:any)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(m.email)&&m.operations.length>0&&m.operations.every((op:string)=>operations.includes(op))))throw new Error('Enter a valid email and operation for each account.');if(new Set(members.map((m:any)=>m.email.toLowerCase())).size!==members.length)throw new Error('Add each email once and select all its operations.');for(const v of Object.values(folders))if(v&&!/^[a-zA-Z0-9_-]+$/.test(v as string))throw new Error('Use a Google Drive folder ID or paste its folder link.');const config={...c.config,folders,members,operations};await db().prepare('UPDATE settings SET value=? WHERE id=?').bind(JSON.stringify(config),'config').run();return Response.json({ok:true});}
 const d={...b.document};delete d.deleted;delete d.deleting;writable(c,d.operation);if(!d.id||!d.knoedlerPart?.trim()||!d.description?.trim())throw new Error('Knoedler Part # and Description are required.');if(JSON.stringify(d).length>1000000)throw new Error('This instruction is too large. Use fewer steps or smaller tables.');
 const old:any=await db().prepare('SELECT * FROM instructions WHERE id=?').bind(d.id).first();if(old){writable(c,old.operation);const status=JSON.parse(old.data);if(status.deleted||status.deleting)throw new Error('This instruction was deleted or deletion is pending. Refresh the list or retry Delete instruction.');if(d.version!==old.version)throw new Error('Someone has updated this instruction. Download your PDF to keep your changes, then reopen the latest version.');}
 const updated=new Date().toISOString();const version=(old?.version||0)+1;const data=JSON.stringify({...d,version,updated});
 if(old){const r=await db().prepare("UPDATE instructions SET data=?,operation=?,version=?,updated=? WHERE id=? AND version=? AND COALESCE(json_extract(data,'$.deleting'),0)=0 AND COALESCE(json_extract(data,'$.deleted'),0)=0").bind(data,d.operation,version,updated,d.id,old.version).run();if(!r.meta.changes)throw new Error('Another user saved first. Reopen the latest version before updating.');}else{await db().prepare('INSERT INTO instructions(id,operation,data,version,updated) VALUES(?,?,?,?,?)').bind(d.id,d.operation,data,version,updated).run();}
 await db().prepare('INSERT INTO revisions(id,instruction_id,data,version,updated) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),d.id,data,version,updated).run();return Response.json({document:{...d,version,updated,driveId:old?.drive_id}});
 }catch(e){return failure(e);}}
export async function PUT(req:Request){try{sameOrigin(req);const c=await context();const f=await req.formData();const id=String(f.get('id'));const row:any=await db().prepare('SELECT * FROM instructions WHERE id=?').bind(id).first();if(!row)throw new Error('Save the instruction before exporting.');writable(c,row.operation);const status=JSON.parse(row.data);if(status.deleted||status.deleting)throw new Error('This instruction was deleted or deletion is pending.');const folder=c.config.folders[row.operation];if(!folder)throw new Error('Your administrator needs to assign a Google Drive folder for this operation.');const pdf=f.get('pdf') as File;if(!pdf||pdf.type!=='application/pdf'||pdf.size>25000000)throw new Error('Upload a PDF smaller than 25 MB.');const d=JSON.parse(row.data);const name=instructionFilename(d);const token=await driveToken();
 const saved=await saveDrivePDF(db(),row,folder,name,pdf,token);return Response.json({ok:true,driveId:saved.id,url:saved.url});}catch(e){return failure(e);}}

export async function DELETE(req:Request){try{sameOrigin(req);const c=await context();const body:any=await req.json();if(typeof body.id!=='string'||!Number.isInteger(body.version))throw new Error('Select a saved instruction to delete.');const row:any=await db().prepare('SELECT * FROM instructions WHERE id=?').bind(body.id).first();if(!row)throw new Error('Instruction not found. Refresh the list.');writable(c,row.operation);return Response.json(await deleteInstruction(db(),row,body.version,driveToken));}catch(e){return failure(e);}}
